version: "3.7"

services:
  api_service:
    build: .
    restart: always
    ports:
      - 8081:8081
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/padel?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=
      - logging.level.org.hibernate.SQL=DEBUG           # Hibernate SQL logging
      - logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE   # Hibernate SQL parameter binding logging
      - logging.level.org.springframework.jdbc=DEBUG   # Spring JDBC logging
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: padel
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

networks:
  springapimysql-net:
